### ISSUE TITLE
Search: event triplication

### ISSUE THREAD

**Issue by agryfp** [pixelache/pixelinfra#7]
While in admin, using search function, yields triplication in events found. Presumably there is only one event in database, rather than 3 which have the same contents

e.g. 
http://pixelache.ac/admin/search 
Enter 'Polymer', yields 1 post and 3 events,

Post: Polymer Scrap and the Limits of the Virtual Body 72 hour live online 24-26.1.
Event: Trashlab Tallinn workshop: Down and Dirty in Polymer
Event: Trashlab Tallinn workshop: Down and Dirty in Polymer
Event: Trashlab Tallinn workshop: Down and Dirty in Polymer

Searching with another term e.g. 'Kaupunkiverstas' features the same triplication of events.

**Comment by agryfp** [comment]
I tried this again
http://pixelache.ac/admin/search
Enter 'Pixelversity', yields 7 posts, 2 pages, 3 events, 1 project
Posts are fine (7 unique posts)
Pages duplicated: Pixelversity
Events tripled again: Pixelversity round-table: Networked Culture & Education Circle

**Comment by cenotaph** [comment]
95% of the Pages in the db are legacy Wordpress pages we need to wipe out or organise better. So I don't think we should include Pages in the pubic search right now. The only root-level pages really are going to be 'About', 'Press' and 'Collaborators' (the latter of which we still need to write). The other pages in the system will be some legacy festival pages, I suppose.

Anyway, I am not getting the search triplication in either search, which means it was probably fixed with issue #9 . The admin-side search is a low priority anyway.
